media_index:
    path:     /
    defaults: { _controller: "EcomerceBackendBundle:Media:index" }
    methods:  GET

media_show:
    path:     /{id}/show
    defaults: { _controller: "EcomerceBackendBundle:Media:show" }
    methods:  GET

media_new:
    path:     /new
    defaults: { _controller: "EcomerceBackendBundle:Media:new" }
    methods:  [GET, POST]

media_edit:
    path:     /{id}/edit
    defaults: { _controller: "EcomerceBackendBundle:Media:edit" }
    methods:  [GET, POST]

media_delete:
    path:     /{id}/delete
    defaults: { _controller: "EcomerceBackendBundle:Media:delete" }
    methods:  DELETE
