<?php

namespace Ecomerce\BackendBundle\Repository;

/**
 * CommandeProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
